#!/bin/zsh

set -eu

BASEDIR=${0:P:h}

source $BASEDIR/../lib/zsh/common.zsh

TEST_DIR=$(mktemp -d)
REF_FILE="${TEST_DIR}/ref"
REF_VALUE=$(grep -E '^ExecStart=echo' $BASEDIR/test.service | cut -f2 -d'"')

cleanup() {
    rm -rf ${TEST_DIR}
}

trap cleanup EXIT

echo $REF_VALUE > $REF_FILE

mkdir -p $BASEDIR/output

sudo raptor make -qb %all

function run-test() {
    local TEST=$1
    local IMAGE=$2
    local NAME=$3
    shift 3

    LOG="Testing ${fg[cyan]}${(r:16:)NAME}${reset_color} [${fg_bold[yellow]}${(r:10:)TEST}${reset_color}: ${fg_bold[white]}${(r:20:)IMAGE}${reset_color}].. "

    MARKER=${TEST_DIR}/marker.${TEST//[\/ ]/-}.${IMAGE//[\/ ]/-}.${NAME//[\/ ]/-}
    truncate -s0 ${MARKER}

    test-${TEST} ${BASEDIR}/${IMAGE} ${NAME} $*

    if grep -qc "$REF_VALUE" ${MARKER}; then
        Info "${LOG}${fg_bold[green]}OK${reset_color}"
    else
        Error "${LOG}${fg_bold[red]}FAIL${reset_color}"
    fi
}

function test-nspawn() {
    local IMAGE=$1
    local NAME=$2
    shift 2

    sudo systemd-nspawn -q --bind $MARKER:/dev/ttyS0 --console=read-only -i ${IMAGE} init > /dev/null
}

function test-portsvc() {
    local IMAGE=$1
    local NAME=$2
    local RUNNER=$3
    shift 3

    local format="raw"
    if [[ ${RUNNER:e} == "qcow2" ]]; then
        format=qcow2
    fi

    test-vm $IMAGE $NAME -drive format=${format},file=${RUNNER},media=cdrom
}

function test-vm() {
    local IMAGE=$1
    local NAME=$2
    shift 2

    local format="raw"
    if [[ ${IMAGE:e} == "qcow2" ]]; then
        format=qcow2
    fi

    sudo kvm \
         -smp cpus=2 \
         -cpu host \
         -machine type=q35,accel=kvm \
         -enable-kvm \
         -boot d \
         -m 2G \
         -serial stdio \
         -display none \
         -drive format=${format},file=${IMAGE} \
         $* > ${MARKER}
}

function test-bios-vm() {
    local IMAGE=$1
    local NAME=$2
    shift 2

    test-vm $IMAGE $NAME
}

function test-uefi-vm() {
    local IMAGE=$1
    local NAME=$2
    shift 2

    test-vm \
        $IMAGE \
        $NAME \
        -smbios type=0,uefi=on \
        -bios /usr/share/OVMF/OVMF_CODE_4M.fd \
        -drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/OVMF_CODE_4M.fd \
        -drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/OVMF_VARS_4M.fd
}

run-test portsvc output/psvc.raw   "Portable service" "output/portable-service-runner.iso" &

run-test nspawn  output/part.img   "Part image" &

run-test nspawn  output/disk.img   "Disk image" &
run-test uefi-vm output/disk.img   "Disk image" &
run-test uefi-vm output/disk.qcow2 "Disk image" &

run-test uefi-vm output/live.img   "Live image" &
run-test uefi-vm output/live.qcow2 "Live image" &

run-test uefi-vm output/live.iso   "Live iso  " &

wait

run-test bios-vm output/live.iso   "Live iso  " &

wait

echo "All tests successful"
